repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (uv)
        entry: uv run ruff check --fix --exit-non-zero-on-fix --no-cache
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format (uv)
        entry: uv run ruff format --no-cache
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: mypy
        name: mypy (uv)
        entry: uv run mypy src
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: pytest
        name: pytest (docker)
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
