"""Native telemt process management.

Responsibilities
----------------
- Download the telemt binary from GitHub Releases (or verify existing).
- Generate mtproxy/config.toml from current Settings + Secrets + Upstreams.
- Start / stop / restart the binary as a foreground subprocess tracked by PID file.
- Stream stdout/stderr to a rotating log.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import tempfile
import textwrap
import time
from pathlib import Path
from typing import Optional

import httpx

from mtproxymaxpy.constants import (
    BINARY_DIR,
    BINARY_NAME,
    BINARY_PATH,
    CONFIG_DIR,
    INSTALL_DIR,
    STATS_DIR,
    TELEMT_DOWNLOAD_URL_TEMPLATE,
    TELEMT_GITHUB_API,
    TELEMT_VERSION,
    TOML_CONFIG_FILE,
)
from mtproxymaxpy.config.settings import Settings, load_settings
from mtproxymaxpy.config.secrets import Secret, load_secrets
from mtproxymaxpy.config.upstreams import Upstream, load_upstreams

logger = logging.getLogger(__name__)

PID_FILE = INSTALL_DIR / "telemt.pid"


# ── Config generation ─────────────────────────────────────────────────────────

def _build_toml_config(
    settings: Settings,
    secrets: list[Secret],
    upstreams: list[Upstream],
    public_ip: str = "",
) -> str:
    """Return a config.toml string for telemt."""
    lines: list[str] = [
        "# Generated by MTProxyMaxPy — do not edit manually",
        f'listen_addr = "0.0.0.0:{settings.proxy_port}"',
        f'metrics_addr = "0.0.0.0:{settings.proxy_metrics_port}"',
        f'concurrency = {settings.proxy_concurrency}',
        f'fake_tls_domain = "{settings.proxy_domain}"',
        f'fake_cert_len = {settings.fake_cert_len}',
        "",
    ]

    if public_ip:
        lines.append(f'public_ip = "{public_ip}"')

    if settings.ad_tag:
        lines.append(f'ad_tag = "{settings.ad_tag}"')

    if settings.masking_enabled:
        lines += [
            "",
            "[masking]",
            f'  host = "{settings.masking_host}"',
            f'  port = {settings.masking_port}',
            f'  unknown_sni_action = "{settings.unknown_sni_action}"',
        ]

    if settings.proxy_protocol:
        lines += [
            "",
            "[proxy_protocol]",
            f'  trusted_cidrs = [{", ".join(repr(c) for c in settings.proxy_protocol_trusted_cidrs.split(",") if c)}]',
        ]

    # Users / secrets
    active = [s for s in secrets if s.enabled]
    if active:
        lines.append("")
        lines.append("[[users]]")
        for s in active:
            lines.append(f'  secret = "{s.key}"  # {s.label}')

    # Upstreams
    active_ups = [u for u in upstreams if u.enabled and u.type != "direct"]
    if active_ups:
        lines.append("")
        for u in active_ups:
            lines += [
                "[[upstream]]",
                f'  name = "{u.name}"',
                f'  type = "{u.type}"',
                f'  addr = "{u.addr}"',
            ]
            if u.user:
                lines.append(f'  user = "{u.user}"')
            if u.password:
                lines.append(f'  password = "{u.password}"')
            lines.append(f'  weight = {u.weight}')
            if u.iface:
                lines.append(f'  interface = "{u.iface}"')

    return "\n".join(lines) + "\n"


def write_toml_config(
    settings: Optional[Settings] = None,
    secrets: Optional[list[Secret]] = None,
    upstreams: Optional[list[Upstream]] = None,
    public_ip: str = "",
) -> None:
    """Regenerate and write config.toml."""
    if settings is None:
        settings = load_settings()
    if secrets is None:
        secrets = load_secrets()
    if upstreams is None:
        upstreams = load_upstreams()

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    STATS_DIR.mkdir(parents=True, exist_ok=True)

    content = _build_toml_config(settings, secrets, upstreams, public_ip)
    fd, tmp = tempfile.mkstemp(dir=CONFIG_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        os.chmod(tmp, 0o600)
        os.replace(tmp, TOML_CONFIG_FILE)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ── Binary management ──────────────────────────────────────────────────────────

def _detect_arch() -> str:
    from mtproxymaxpy.utils.system import get_arch
    return get_arch()


def _resolve_download_url(version: str = TELEMT_VERSION) -> str:
    arch = _detect_arch()
    return TELEMT_DOWNLOAD_URL_TEMPLATE.format(version=version, arch=arch)


def get_latest_version() -> str:
    """Query GitHub API for the latest telemt release tag."""
    try:
        resp = httpx.get(TELEMT_GITHUB_API, timeout=10)
        resp.raise_for_status()
        tag = resp.json().get("tag_name", f"v{TELEMT_VERSION}")
        return tag.lstrip("v")
    except Exception:
        return TELEMT_VERSION


def is_binary_present() -> bool:
    return BINARY_PATH.exists() and os.access(BINARY_PATH, os.X_OK)


def download_binary(version: str = TELEMT_VERSION, force: bool = False) -> None:
    """Download the telemt binary. Skips if already present and *force* is False."""
    if is_binary_present() and not force:
        logger.info("telemt binary already present at %s", BINARY_PATH)
        return

    BINARY_DIR.mkdir(parents=True, exist_ok=True)
    url = _resolve_download_url(version)
    logger.info("Downloading telemt %s from %s …", version, url)

    tmp_path = BINARY_DIR / (BINARY_NAME + ".tmp")
    try:
        with httpx.stream("GET", url, timeout=60, follow_redirects=True) as resp:
            resp.raise_for_status()
            with open(tmp_path, "wb") as fh:
                for chunk in resp.iter_bytes(chunk_size=65536):
                    fh.write(chunk)
        os.chmod(tmp_path, 0o755)
        os.replace(tmp_path, BINARY_PATH)
        logger.info("telemt saved to %s", BINARY_PATH)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise


# ── Process lifecycle ──────────────────────────────────────────────────────────

def _read_pid() -> Optional[int]:
    try:
        return int(PID_FILE.read_text().strip())
    except Exception:
        return None


def _write_pid(pid: int) -> None:
    PID_FILE.write_text(str(pid))


def _clear_pid() -> None:
    PID_FILE.unlink(missing_ok=True)


def is_running() -> bool:
    """Return True if the tracked telemt process is alive."""
    pid = _read_pid()
    if pid is None:
        return False
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False


def get_pid() -> Optional[int]:
    return _read_pid() if is_running() else None


def start(*, regenerate_config: bool = True, public_ip: str = "") -> int:
    """Start the telemt binary. Returns the new PID."""
    if is_running():
        pid = _read_pid()
        logger.info("telemt already running (PID %s)", pid)
        return pid  # type: ignore[return-value]

    if not is_binary_present():
        raise FileNotFoundError(
            f"telemt binary not found at {BINARY_PATH}. run 'mtproxymaxpyPy install' first."
        )

    if regenerate_config:
        write_toml_config(public_ip=public_ip)

    log_file = INSTALL_DIR / "telemt.log"
    with open(log_file, "ab") as log_fh:
        proc = subprocess.Popen(
            [str(BINARY_PATH), "--config", str(TOML_CONFIG_FILE)],
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    _write_pid(proc.pid)
    # Brief wait to detect immediate crash
    time.sleep(0.5)
    if proc.poll() is not None:
        _clear_pid()
        raise RuntimeError(f"telemt exited immediately with code {proc.returncode}")

    logger.info("telemt started (PID %s)", proc.pid)
    return proc.pid


def stop(timeout: float = 10.0) -> None:
    """Send SIGTERM to telemt and wait up to *timeout* seconds."""
    pid = _read_pid()
    if pid is None:
        return
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        _clear_pid()
        return

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            break
        time.sleep(0.2)
    else:
        try:
            os.kill(pid, signal.SIGKILL)
        except ProcessLookupError:
            pass

    _clear_pid()
    logger.info("telemt stopped (was PID %s)", pid)


def restart(**start_kwargs) -> int:
    """Stop then start telemt."""
    stop()
    return start(**start_kwargs)


def status() -> dict:
    """Return a status dict: running, pid, binary_present, config_exists."""
    return {
        "running": is_running(),
        "pid": get_pid(),
        "binary_present": is_binary_present(),
        "config_exists": TOML_CONFIG_FILE.exists(),
    }
