"""Native telemt process management.

Responsibilities
----------------
- Download the telemt binary from GitHub Releases (or verify existing).
- Generate mtproxy/config.toml from current Settings + Secrets + Upstreams.
- Start / stop / restart the binary as a foreground subprocess tracked by PID file.
- Stream stdout/stderr to a rotating log.
"""

from __future__ import annotations

import logging
import os
import re
import signal
import subprocess
import tarfile
import tempfile
import time
from datetime import UTC, date, datetime
from typing import Any

import httpx

from mtproxymaxpy.config.secrets import Secret, load_secrets
from mtproxymaxpy.config.settings import Settings, load_settings
from mtproxymaxpy.config.upstreams import Upstream, load_upstreams
from mtproxymaxpy.constants import (
    BINARY_DIR,
    BINARY_NAME,
    BINARY_PATH,
    CONFIG_DIR,
    INSTALL_DIR,
    STATS_DIR,
    TELEMT_DOWNLOAD_URL_TEMPLATE,
    TELEMT_GITHUB_API,
    TELEMT_VERSION,
    TOML_CONFIG_FILE,
)

logger = logging.getLogger(__name__)

PID_FILE = INSTALL_DIR / "telemt.pid"


def _to_rfc3339_expiration(value: str) -> str | None:
    """Convert secret expiry to an RFC 3339 timestamp expected by telemt."""
    raw = value.strip()
    if raw in ("", "0"):
        return None

    # Internal canonical format is YYYY-MM-DD.
    try:
        d = date.fromisoformat(raw)
        return f"{d.isoformat()}T23:59:59Z"
    except ValueError:
        pass

    # Allow datetime input and normalize timezone to RFC 3339.
    dt_raw = raw[:-1] + "+00:00" if raw.endswith("Z") else raw
    try:
        dt = datetime.fromisoformat(dt_raw)
    except ValueError:
        return None

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt.isoformat().replace("+00:00", "Z")


# ── Config generation ─────────────────────────────────────────────────────────


def _build_toml_config(
    settings: Settings,
    secrets: list[Secret],
    upstreams: list[Upstream],
    public_ip: str = "",
) -> str:
    """Return a config.toml string for telemt matching the bash-generated format."""
    active = [s for s in secrets if s.enabled]

    lines: list[str] = [
        "# Generated by MTProxyMaxPy — do not edit manually",
        f"# {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "[general]",
        "prefer_ipv6 = false",
        "fast_mode = true",
        "use_middle_proxy = true",
        'log_level = "normal"',
    ]

    if settings.ad_tag:
        lines.append(f'ad_tag = "{settings.ad_tag}"')
    else:
        lines.append('# ad_tag = ""  # Get from @MTProxyBot')

    lines += [
        "",
        "[general.modes]",
        "classic = false",
        f"secure = {'true' if not settings.masking_enabled else 'false'}",
        "tls = true",
    ]

    if active:
        labels_quoted = ", ".join(f'"{s.label}"' for s in active)
        lines += [
            "",
            "[general.links]",
            f"show = [{labels_quoted}]",
        ]

    lines += [
        "",
        "[server]",
        f"port = {settings.proxy_port}",
        'listen_addr_ipv4 = "0.0.0.0"',
        'listen_addr_ipv6 = "::"',
        f"proxy_protocol = {'true' if settings.proxy_protocol else 'false'}",
    ]

    if settings.proxy_protocol and settings.proxy_protocol_trusted_cidrs:
        cidrs = [c.strip() for c in settings.proxy_protocol_trusted_cidrs.split(",") if c.strip()]
        cidrs_str = ", ".join(f'"{c}"' for c in cidrs)
        lines.append(f"proxy_protocol_trusted_cidrs = [{cidrs_str}]")

    lines += [
        f"metrics_port = {settings.proxy_metrics_port}",
        'metrics_whitelist = ["127.0.0.1", "::1"]',
        "",
        "[timeouts]",
        "client_handshake = 30",
        "tg_connect = 10",
        "client_keepalive = 15",
        "client_ack = 90",
        "",
        "[censorship]",
        f'tls_domain = "{settings.proxy_domain}"',
        f'unknown_sni_action = "{settings.unknown_sni_action}"',
        f"mask = {'true' if settings.masking_enabled else 'false'}",
        f"mask_port = {settings.masking_port}",
    ]

    if settings.masking_enabled and settings.masking_host:
        lines.append(f'mask_host = "{settings.masking_host}"')

    lines += [
        f"fake_cert_len = {settings.fake_cert_len}",
        "",
        "[access]",
        "replay_check_len = 65536",
        "replay_window_secs = 1800",
        "ignore_time_skew = false",
    ]

    # [access.users] — "label" = "hexkey"
    if active:
        lines += ["", "[access.users]"]
        for s in active:
            lines.append(f'"{s.label}" = "{s.key}"')

    # Per-user limit sections keyed by label
    max_conns = {s.label: s.max_conns for s in active if s.max_conns > 0}
    max_ips = {s.label: s.max_ips for s in active if s.max_ips > 0}
    quota = {s.label: s.quota_bytes for s in active if s.quota_bytes > 0}
    expires: dict[str, str] = {}
    for s in active:
        exp = _to_rfc3339_expiration(s.expires)
        if exp:
            expires[s.label] = exp
        elif s.expires.strip() not in ("", "0"):
            logger.warning("Skipping invalid expiry for secret label=%s: %r", s.label, s.expires)

    if max_conns:
        lines += ["", "[access.user_max_tcp_conns]"]
        for label, val in max_conns.items():
            lines.append(f'"{label}" = {val}')
    if max_ips:
        lines += ["", "[access.user_max_unique_ips]"]
        for label, val in max_ips.items():
            lines.append(f'"{label}" = {val}')
    if quota:
        lines += ["", "[access.user_data_quota]"]
        for label, val in quota.items():
            lines.append(f'"{label}" = {val}')
    if expires:
        lines += ["", "[access.user_expirations]"]
        for label, exp_str in expires.items():
            lines.append(f'"{label}" = "{exp_str}"')

    # Upstreams
    active_ups = [u for u in upstreams if u.enabled and u.type != "direct"]
    if active_ups:
        for u in active_ups:
            lines += [
                "",
                "[[upstreams]]",
                f'type = "{u.type}"',
                f"weight = {u.weight}",
            ]
            if u.addr:
                lines.append(f'address = "{u.addr}"')
            if u.user:
                if u.type == "socks4":
                    lines.append(f'user_id = "{u.user}"')
                else:
                    lines.append(f'username = "{u.user}"')
            if u.password:
                lines.append(f'password = "{u.password}"')
            if u.iface:
                lines.append(f'interface = "{u.iface}"')

    return "\n".join(lines) + "\n"


def write_toml_config(
    settings: Settings | None = None,
    secrets: list[Secret] | None = None,
    upstreams: list[Upstream] | None = None,
    public_ip: str = "",
) -> None:
    """Regenerate and write config.toml."""
    if settings is None:
        settings = load_settings()
    if secrets is None:
        secrets = load_secrets()
    if upstreams is None:
        upstreams = load_upstreams()

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    STATS_DIR.mkdir(parents=True, exist_ok=True)

    content = _build_toml_config(settings, secrets, upstreams, public_ip)
    fd, tmp = tempfile.mkstemp(dir=CONFIG_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        os.chmod(tmp, 0o600)
        os.replace(tmp, TOML_CONFIG_FILE)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


# ── Binary management ──────────────────────────────────────────────────────────


def _detect_arch() -> str:
    from mtproxymaxpy.utils.system import get_arch

    return get_arch()


def _resolve_download_url(version: str = TELEMT_VERSION) -> str:
    arch = _detect_arch()
    return TELEMT_DOWNLOAD_URL_TEMPLATE.format(version=version, arch=arch)


def get_latest_version() -> str:
    """Query GitHub API for the latest telemt release tag."""
    try:
        resp = httpx.get(TELEMT_GITHUB_API, timeout=10)
        resp.raise_for_status()
        tag = resp.json().get("tag_name", f"v{TELEMT_VERSION}")
        return str(tag).lstrip("v")
    except (httpx.HTTPError, OSError, ValueError, RuntimeError):
        return TELEMT_VERSION


def get_binary_version(default: str = TELEMT_VERSION) -> str:
    """Return installed telemt version parsed from `telemt --version` output."""
    if not is_binary_present():
        return default

    try:
        res = subprocess.run(
            [str(BINARY_PATH), "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return default

    text = (res.stdout + res.stderr).strip()
    match = re.search(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", text)
    return match.group(0) if match else default


def is_binary_present() -> bool:
    return BINARY_PATH.exists() and os.access(BINARY_PATH, os.X_OK)


def download_binary(version: str = TELEMT_VERSION, force: bool = False) -> None:
    """Download and extract the telemt binary. Skips if already present and *force* is False."""
    if is_binary_present() and not force:
        logger.info("telemt binary already present at %s", BINARY_PATH)
        return

    BINARY_DIR.mkdir(parents=True, exist_ok=True)
    url = _resolve_download_url(version)
    logger.info("Downloading telemt %s from %s …", version, url)

    tar_tmp = BINARY_DIR / (BINARY_NAME + ".tar.gz.tmp")
    bin_tmp = BINARY_DIR / (BINARY_NAME + ".tmp")
    try:
        with httpx.stream("GET", url, timeout=120, follow_redirects=True) as resp:
            resp.raise_for_status()
            with open(tar_tmp, "wb") as fh:
                for chunk in resp.iter_bytes(chunk_size=65536):
                    fh.write(chunk)

        # Extract the 'telemt' binary from the archive
        with tarfile.open(tar_tmp, "r:gz") as tf:
            member = next(
                (m for m in tf.getmembers() if m.name.endswith(BINARY_NAME) or m.name == BINARY_NAME),
                None,
            )
            if member is None:
                raise RuntimeError(f"Could not find '{BINARY_NAME}' in downloaded archive")
            src = tf.extractfile(member)
            if src is None:
                raise RuntimeError(f"Failed to read '{BINARY_NAME}' from archive")
            with open(bin_tmp, "wb") as fh:
                fh.write(src.read())

        tar_tmp.unlink(missing_ok=True)
        os.chmod(bin_tmp, 0o755)
        os.replace(bin_tmp, BINARY_PATH)
        logger.info("telemt saved to %s", BINARY_PATH)
    except Exception:
        try:
            tar_tmp.unlink(missing_ok=True)
            bin_tmp.unlink(missing_ok=True)
        except OSError:
            pass
        raise


# ── Process lifecycle ──────────────────────────────────────────────────────────


def _read_pid() -> int | None:
    try:
        return int(PID_FILE.read_text().strip())
    except (OSError, ValueError):
        return None


def _write_pid(pid: int) -> None:
    PID_FILE.write_text(str(pid))


def _clear_pid() -> None:
    PID_FILE.unlink(missing_ok=True)


def is_running() -> bool:
    """Return True if the tracked telemt process is alive."""
    pid = _read_pid()
    if pid is None:
        return False
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError):
        return False


def get_pid() -> int | None:
    return _read_pid() if is_running() else None


def start(*, regenerate_config: bool = True, public_ip: str = "") -> int:
    """Start the telemt binary. Returns the new PID."""
    if is_running():
        pid = _read_pid()
        logger.info("telemt already running (PID %s)", pid)
        return pid  # type: ignore[return-value]

    if not is_binary_present():
        raise FileNotFoundError(f"telemt binary not found at {BINARY_PATH}. Run 'mtproxymaxpy install' first.")

    if regenerate_config:
        write_toml_config(public_ip=public_ip)

    log_file = INSTALL_DIR / "telemt.log"
    with open(log_file, "ab") as log_fh:
        proc = subprocess.Popen(
            [str(BINARY_PATH), str(TOML_CONFIG_FILE)],
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    _write_pid(proc.pid)
    # Brief wait to detect immediate crash
    time.sleep(0.5)
    if proc.poll() is not None:
        _clear_pid()
        raise RuntimeError(f"telemt exited immediately with code {proc.returncode}")

    logger.info("telemt started (PID %s)", proc.pid)
    return proc.pid


def stop(timeout: float = 10.0) -> None:
    """Send SIGTERM to telemt and wait up to *timeout* seconds."""
    pid = _read_pid()
    if pid is None:
        return
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        _clear_pid()
        return

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            break
        time.sleep(0.2)
    else:
        try:
            os.kill(pid, signal.SIGKILL)  # type: ignore[attr-defined]
        except ProcessLookupError:
            pass

    _clear_pid()
    logger.info("telemt stopped (was PID %s)", pid)


def restart(*, regenerate_config: bool = True, public_ip: str = "") -> int:
    """Stop then start telemt."""
    stop()
    return start(regenerate_config=regenerate_config, public_ip=public_ip)


def reload_config() -> None:
    """Send SIGHUP to the running telemt process to reload config without restart."""
    pid = _read_pid()
    if pid is None or not is_running():
        raise RuntimeError("telemt is not running")
    try:
        os.kill(pid, signal.SIGHUP)  # type: ignore[attr-defined]
        logger.info("Sent SIGHUP to telemt (PID %s)", pid)
    except ProcessLookupError:
        _clear_pid()
        raise RuntimeError("telemt process not found")


def status() -> dict[str, Any]:
    """Return a status dict: running, pid, binary_present, config_exists."""
    pid = get_pid()
    uptime_sec: int | None = None
    if pid:
        try:
            import psutil  # type: ignore[import-untyped]  # noqa: PLC0415
        except ImportError:
            psutil = None
        if psutil is not None:
            try:
                p = psutil.Process(pid)
                uptime_sec = int(time.time() - p.create_time())
            except (OSError, psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                logger.debug("Failed to get process uptime", exc_info=True)
    return {
        "running": is_running(),
        "pid": pid,
        "binary_present": is_binary_present(),
        "config_exists": TOML_CONFIG_FILE.exists(),
        "uptime_sec": uptime_sec,
    }
